spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/${GITHUB_USER_NAME}/${GITHUB_REPO_NAME}
          username: ${GITHUB_USER_NAME}
          password: ${GITHUB_PASSWORD}
          default-label: main

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"